meta_product_name: "Owen Baldwin"
meta_title: "Film composer and songwriter"
meta_description: "Owen Baldwin is a freelance film composer and songwriter"
meta_image: "owen-baldwin-og.png" # should exist in `app/assets/images/`
twitter_account: "@OwenABaldwin1"   # required for Twitter Cards
